project:
  type: website
  output-dir: docs

website:
  title: "AMMnet Kigali 2024"
  navbar:
    left:
      - href: r_installation_all.qmd
        text: R Installation Instructions

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

